### ISSUE TITLE
almost every example runs with a black window (macOS 10.14.1  ,  go 1.11)

### ISSUE THREAD

**Issue by SmileEye** [faiface/pixel-examples#15]
Does anyone have the same problem as me ？

**Comment by faiface** [comment]
Yeah, OpenGL is becoming buggy on MacOS, because they're dropping the support, which sucks. Not sure what to do about that exactly.

**Comment by SmileEye** [comment]
Thank you very much for your reply,  I will try to learn this open source software on Windows
