### ISSUE TITLE
"cannot find package" trying to run examples

### ISSUE THREAD

**Issue by cheshire137** [faiface/pixel-examples#17]
Hi! I'm getting an error with each example I try to run:

```sh
Downloads/pixel-examples/typewriter at wonderland (master ✔)
% go run main.go
main.go:11:2: cannot find package "github.com/faiface/pixel" in any of:
	/usr/local/go/src/github.com/faiface/pixel (from $GOROOT)
	/Users/cheshire137/code/go/src/github.com/faiface/pixel (from $GOPATH)
```

I'm using macOS with:

```
% go version
go version go1.13.4 darwin/amd64
```

Do I need to clone faiface/pixel somewhere, or have a particular `$GOROOT` environment variable?

**Comment by scottlawsonbc** [comment]
If anyone else encounters this issue, here is how you can fix it. I'll use the platformer as an example.

In the platformer directory, run `go mod init github.com/faiface/pixel-examples/platformer`
The output should be `go: creating new go.mod: module github.com/faiface/pixel-examples/platformer`

Next run `go build`. When it finishes, you can run `go run .` to start the demo.

**Comment by vrecan** [comment]
would be nice if someone updated  the repo to use go mod for all the examples

**Comment by willbeason** [comment]
I've created #20 to resolve this. Since this repo doesn't get much traffic I'll post an issue in the main repository linking here.

**Comment by PawBud** [comment]
![Screenshot from 2021-05-04 00-26-45](https://user-images.githubusercontent.com/48093317/116919880-9240ce00-ac6f-11eb-94fc-7c32c5517ccc.png)
this is what I am getting, after trying out the "Creating a Window" Example and using https://github.com/faiface/pixel-examples/issues/17#issuecomment-626273076
