### ISSUE TITLE
High GPU usage running sudoku example

### ISSUE THREAD

**Issue by fourst4r** [faiface/pixel-examples#7]
I have not experienced this with the other examples.
This is what it looks like after a minute: https://i.imgur.com/BwAwD8A.png

Possibly caused by line 185-200 (not re-using text.Texts)
```go
for a, sa := range board {
	for b, sb := range sa {
		if sb != 0 {
			num := text.New(pixel.ZV, atlas)
			num.WriteString(strconv.Itoa(sb))
			num.DrawColorMask(batch,
				pixel.IM.
					Scaled(
						pixel.ZV, float64(width)/900).
					Moved(
						pixel.V((float64(a)+0.3)*width/9,
							(float64(b)+0.25)*width/9)),
				colornames.Black)
		}
	}
}
```

ping @jwangsadinata

**Comment by faiface** [comment]
Hey, sorry for not responding sooner, somehow forgot about this. If you know how to fix it, would be be so kind and make a PR?

**Comment by jwangsadinata** [comment]
Hey @fourst4r, so sorry for missing the issue that you pinged. It seems that it was just buried in my emails, until faiface's comment above.

You raised a good point on re-using `text.Text`, definitely an oversight on my part and I'll write a follow up PR on this and ask for your review. My other hunch is that the `text.DrawColorMask` is rather an expensive operation, especially with the transformation above, although I have to look into it first. But your suggestion is definitely worth an initial follow up PR for sure.

**Comment by faiface** [comment]
Thanks, @jwangsadinata, I merged your PR! The function `text.DrawColorMask` should be a problem, it's pretty fast. In fact, `text.Draw` just calls `text.DrawColorMask`.
